### ISSUE TITLE
Not compatible with scipy 1.0.0

### ISSUE THREAD

**Issue by lamping7** [dronecrew/ulog_tools#3]
Needed to downgrade to 0.19.1. Error below:

```
$ ulog_tools_pid_design --url http://review.px4.io/download?log=d3980cdd-c8ef-478b-a838-fba9956009c4 out.gains

Traceback (most recent call last):
  File "/home/tony/.local/bin/ulog_tools_pid_design", line 11, in <module>
    sys.exit(main())
  File "/home/tony/.local/lib/python3.5/site-packages/ulog_tools/control_opt.py", line 84, in main
    est_delay=est_delay
  File "/home/tony/.local/lib/python3.5/site-packages/ulog_tools/control_opt.py", line 29, in attitude_loop_design
    G=G_rate_ol, K_guess=[0.2, 0.2, 0], dcut_hz=dcut_hz)
  File "/home/tony/.local/lib/python3.5/site-packages/ulog_tools/_lqrofb.py", line 157, in pid_design
    K = lqr_ofb_design(K_guess, ss_open, verbose)
  File "/home/tony/.local/lib/python3.5/site-packages/ulog_tools/_lqrofb.py", line 106, in lqr_ofb_design
    constraints=constraints
  File "/home/tony/.local/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 495, in minimize
    constraints, callback=callback, **options)
  File "/home/tony/.local/lib/python3.5/site-packages/scipy/optimize/slsqp.py", line 378, in _minimize_slsqp
    fx = func(x)
  File "/home/tony/.local/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/home/tony/.local/lib/python3.5/site-packages/ulog_tools/_lqrofb.py", line 55, in lqr_ofb_cost
    P = scipy.linalg.solve_lyapunov(A_c.T, -Q_c)
AttributeError: module 'scipy.linalg' has no attribute 'solve_lyapunov'
```

**Comment by neom89** [comment]
@lamping7 Can you please help with the terminal command for downgrading scipy.linalg?

**Comment by lamping7** [comment]
@vmishra9 try `pip3 install --user scipy==0.19.1` (assuming you didn't install the package with sudo)

**Comment by neom89** [comment]
Thanks. I get this comment:
Requirement already satisfied: scipy==0.19.1 in /anaconda3/lib/python3.6/site-packages

But I get the same error as you when I run "ulog_tools_pid_design"

**Comment by lamping7** [comment]
I can't step you through troubleshooting this, but your python path is pointing to different places. It looks like you have multiple versions of scipy installed for different environments. I'm not sure of your env or how you installed the package.
EDIT: This is a guess due to the conda path.

**Comment by jgoppert** [comment]
Check out binder, working with scipy=1.4.1=py37h921218d
